user-message: "WARNING: This stack project is generated."

flags:
  hlint:
    ghc-lib: false
  ghc-lib-parser-ex:
    no-ghc-lib: true

resolver: lts-19.33

# We have 1 package.
packages:
  - ./.

extra-deps: []
